### ISSUE TITLE
ClassDefNotFoundException

### ISSUE THREAD

**Issue by elioth010** [LivotovLabs/zxscanlib#16]
Whats is happend?

01-23 10:33:25.272: E/AndroidRuntime(13703): 	Suppressed: java.lang.ClassNotFoundException: eu.livotov.labs.android.camview.CAMView

**Comment by livotov** [comment]
zxscanlib depends on a CAMView project, please make sure you added {transitive=true} into your compile statement as described in readme

**Comment by elioth010** [comment]
@livotov, Thanks now its work properly, nice work.
