### ISSUE TITLE
Flash Light

### ISSUE THREAD

**Issue by panagorn** [LivotovLabs/zxscanlib#17]
hello i want to ask if it is easy to add a function thats its opens and closes the flash light of the camera.
Thank you in advance

**Comment by livotov** [comment]
good  idea. will extend set of configurable options shortly

**Comment by panagorn** [comment]
ok thank you

**Comment by panagorn** [comment]
Hello i have notice that you released the v2 and i want to ask if you added a function for the flash. thank you

**Comment by livotov** [comment]
No, just released 2.0.0 to force sdk 21 upgrade things. Flashlight, etc will go shortly to 2.0.1.
Sorry, did not update the milestone

**Comment by panagorn** [comment]
OK thank you. I will be waiting for this feature. Great job

**Comment by livotov** [comment]
the 2.0.1 snapshot will be available in a day or two, you should see and be able to test the flashlight issue there

**Comment by Jakevin** [comment]
I try to add flash function in lib, but is very slowly...

```java
public void setFlash(boolean isOpen) {
        Camera mCamera = mScannerView.getCamera().getCamera();
        if (mCamera != null && CameraUtils.isFlashSupported(mCamera)) {
            Camera.Parameters parameters = mCamera.getParameters();
            if (isOpen) {
                if (parameters.getFlashMode().equals(Camera.Parameters.FLASH_MODE_TORCH)) {
                    return;
                }
                parameters.setFlashMode(Camera.Parameters.FLASH_MODE_TORCH);
            } else {
                if (parameters.getFlashMode().equals(Camera.Parameters.FLASH_MODE_OFF)) {
                    return;
                }
                parameters.setFlashMode(Camera.Parameters.FLASH_MODE_OFF);
            }
            mCamera.setParameters(parameters);
        }
    }
```

**Comment by panagorn** [comment]
why is that happening?

**Comment by livotov** [comment]
Flash support added into CAMView project (both master and 1.0.3-SNAPSHOT).
Current ZXScanLib 2.0.1-SNAPSHOT was also switched to CAMView snapshot version, mentioned above. The usage is: 

ScannerView scanner = findViewById(....);
...
scanner.getCamera().switchFlash(boolean)

Note, that switchFlash method should be called only when the camera is active.
