### ISSUE TITLE
standalone mode

### ISSUE THREAD

**Issue by TheLoyalCruel** [LivotovLabs/zxscanlib#20]
standalone mode does not work! app crash!

**Comment by livotov** [comment]
Even in the bundled demo app ?
And embedded mode works fine, right  ?

**Comment by livotov** [comment]
Never mind, was able to reproduce it.
Thanks, fixed both in master and in 2.0.1-SNAPSHOT now.

**Comment by TheLoyalCruel** [comment]
Tnx Buddy... :)

**Comment by TheLoyalCruel** [comment]
another question:
i want to add your library into my project but it has this error:
Error:Configuration with name 'default' not found.
i added the dependency i don't why it happens!

**Comment by livotov** [comment]
could you please show me your gradle file ?

**Comment by TheLoyalCruel** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10336613/7366799/e064af1e-edaf-11e4-8aa8-1afc697baca8.jpg)
![untitled2](https://cloud.githubusercontent.com/assets/10336613/7366800/e06bda6e-edaf-11e4-8909-a06ae9f1a376.jpg)


tnx...

**Comment by livotov** [comment]
Basically, you should just link the library from our maven repository with the compile statement:
compile ('eu.livotov.labs:zxscanlib:2.0.0@aar') {transitive=true} , just see the README.md for more info.

But if you want to include it locally, include just the zxscanlib module, not the entire project (e.g. zxscanlib/zxscanlib ), as the main zxscanlib folder contains two modules - library and a demo app and it looks like you're trying to include this folder instead of the library module.

**Comment by TheLoyalCruel** [comment]
i want to include it locally! i did exactly the same you said! but the error is with me again...
i commented out this line in library gradle:
//apply from: 'https://raw.github.com/chrisbanes/gradle-mvn-push/master/gradle-mvn-push.gradle'
and the error changed into this:
![screenshot 2015-04-28 17 13 58](https://cloud.githubusercontent.com/assets/10336613/7369799/041f5200-edca-11e4-93ab-2056fc156ac4.png)

i'm sorry i'm confused with this...!

**Comment by livotov** [comment]
In order to use it from maven, you have to add maven repo server url:

maven { url 'http://maven.livotovlabs.pro/content/groups/public' }

**Comment by livotov** [comment]
note, that zxscanlib depends on another library - the CAMView. So if you want everything locally, you have to download and include that library as well.

**Comment by TheLoyalCruel** [comment]
the maven is set by default...
would you please tell me, where the CAMVIew library is?
and where should i import this?

**Comment by livotov** [comment]
https://github.com/LivotovLabs/CamView

**Comment by livotov** [comment]
again, if you're using maven repo, you just need to import ZXScanLib only, as mentioned in README.md. If you want to have everything locally, then you have to sort it out manually and import both modules from folders.

**Comment by TheLoyalCruel** [comment]
it works...
and flash control is so helpful. tnx for your help :)

**Comment by livotov** [comment]
Glad it helped !
