### ISSUE TITLE
Gradle build failed and difficult in getting it started

### ISSUE THREAD

**Issue by deepdoradla** [LivotovLabs/zxscanlib#21]
Hi,

I have tried adding the library to my project but I am unable to so. 

I am a little new to android dev as well. Kindly help me sort this out. Really appreciate your time.

When I try syncing the gradle file, this is the error I am getting

```
Error:Execution failed for task ':app:processDebugManifest'.
> Multiple entries with same key: android:label=REPLACE and tools:label=REPLACE
```

Here is my gradle file.
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"

    defaultConfig {
        applicationId "com.acssl.testpackage"
        minSdkVersion 14
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    dexOptions {
        preDexLibraries = false
    }

}

repositories {
    mavenCentral()
    maven { url 'http://maven.livotovlabs.pro/content/groups/public' }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:recyclerview-v7:21.0.+'
    compile 'com.android.support:cardview-v7:21.0+'
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.0.0'
    compile 'com.squareup.okhttp:okhttp:2.0.0'
    compile 'com.squareup.picasso:picasso:2.5.0'
    compile 'com.facebook.android:facebook-android-sdk:3.21.1'
    compile 'com.google.zxing:core:3.2.0'
    compile 'com.android.support:appcompat-v7:22.0.0'
    compile 'com.google.android.gms:play-services:7.0.0'
    compile files('libs/zbar.jar')
    compile 'eu.livotov.labs:camview:1.0.3-SNAPSHOT@aar'
    compile 'eu.livotov.labs:zxscanlib:2.0.0@aar' {transitive=true}
}
```

**Comment by livotov** [comment]
Hi !
Try using latest zxscanlib v 2.0.1-SNAPSHOT
It contains a fix for such situation.

P.S. And you don't need to include camview manually, because zxscanlib will do this for you automatically.

**Comment by deepdoradla** [comment]
Thanks for the quick reply.

I just tried with v 2.0.1. Below is the error I am receiving. Please guide

```
Error:(44, 14) Failed to resolve: eu.livotov.labs:zxscanlib:2.0.1
```
This is how I added dependency to gradle
```
compile ('eu.livotov.labs:zxscanlib:2.0.1@aar') {transitive=true}
```

This is how I added maven url
```
repositories {
    mavenCentral()
    maven { url 'http://maven.livotovlabs.pro/content/groups/public' }
}
```

**Comment by deepdoradla** [comment]
Is there any other way to add this cool library to my project ?

**Comment by livotov** [comment]
2.0.1-SNAPSHOT, not just 2.0.1

compile ('eu.livotov.labs:zxscanlib:2.0.1-SNAPSHOT@aar') {transitive=true}

**Comment by deepdoradla** [comment]
ahhh my bad ... thats silly. It worked.

In order to extend ScannerView, do I have to include scannerView.java manually?

Because it says there is no default constructor available in eu.livotov.zxscan.ScannerView.

**Comment by livotov** [comment]
Practically, ScanTestActivity should not extend ScannerView. ScannerView is a view ( an UI  component). You should create your activity as usual and add the ScannerView into the layout, like any other view (TextView, Button, etc.). Please see the demo app bundled for sample.

If you want to extend ScannerView to tweak/provide your custom functions - just extend it, like MyScannerView extends ScannerView. Yes, you have to provide a non-default constructor invoke super in it. But the still use your MyScannerView as usual in layout.

**Comment by tlemansec** [comment]
hello, i have the same problem mentionned before, but compile ('eu.livotov.labs:zxscanlib:2.0.1-SNAPSHOT@aar') {transitive=true} didn't work for me. I have the error of type "Failed to resolve".

Do you know where the problem can come from?

thanks

**Comment by livotov** [comment]
Please check the readme, current snapshot version is 2.1.0 at the moment. Current stable version is 2.0.1

note, that once new snapshot is uploaded, previous one is removed automatically.

**Comment by tlemansec** [comment]
thanks for the quick answer.

I read the readme, but i still fail to resolve the lib.

**Comment by livotov** [comment]
check you did not forget to add the maven repo url as well

**Comment by tlemansec** [comment]
humm sorry, i've missed that point... thanks for the help!
