### ISSUE TITLE
custom size to scannerview stretches the preview.

### ISSUE THREAD

**Issue by kailash09dabhi** [LivotovLabs/zxscanlib#22]
When setting custom size to scannerview  . Camera preview is stretched .It should not stretch . Is there any solution so preview look normal.?

I observed that when scannerview is match_parent , the camera preview is perfect. But when i try to set its size to half of the height of device then it stretches the camera preview. Please guide me.

**Comment by livotov** [comment]
Basically, it should adapt custom size and select one of supported streaming formats from the camera and keep the ratio. (with the black fields on h/v sides). Will check it, thanks for reporting.

So you're simply setting the ScanView size to some fixed values in your layout, like  XXXdp, YYYdp, right ?

**Comment by kailash09dabhi** [comment]
Actually i have put the Scannerview in Linearlayout and given weight 1 and listview iwth weight 1. 
In short I need scanner half sized and half sized listview so i can instantly scan and show value in listview

**Comment by nateridderman** [comment]
I've also noticed the stretching and I'm using fixed dp values.

**Comment by mtangoo** [comment]
Ping ......!
It happens with me too!

**Comment by livotov** [comment]
Pong !
this issue is already in progress, stay tuned )

**Comment by mtangoo** [comment]
Thanks!

**Comment by livotov** [comment]
IMPORTANT INFORMATION - this project is now merged with another one, called CAMView: https://github.com/LivotovLabs/CamView

All future development of this scanner library will happen inside the CAMView repository. Please post your issues and download sources, new snapshots and releases there: https://github.com/LivotovLabs/CamView

We believe both ZXScanLib and CAMView have a lot of common (moreover, ZXScanLib depends on a CAMView), so having it as a single solid project will boost productivity and add more transparency.

All previous ZXScanLib releases will remain in the maven repo forever, so no current production apps should be affected.
