### ISSUE TITLE
OnBackPressed() never called by zxscanlib 

### ISSUE THREAD

**Issue by aaronbond** [LivotovLabs/zxscanlib#23]
back button doesn't work when using a fragment embedding zxscanlib

**Comment by livotov** [comment]
ScannerFragment does not intercept back button events, so it is probably you're doing smth custom with the back button in your app.  

Check the demo app, bundled with the project, back button works normally there. Also note, that ScannerFragment stops the camera in onPause method and this may take some extra time which may look like activity is not responding to a back button.

**Comment by wsgfz** [comment]
I think this is because the decoder is working at the main thread.

**Comment by livotov** [comment]
hm, good point!

**Comment by aaronbond** [comment]
this is what i was thinking.

also there's a point in the camview project (on which this project depends) where a buffer is not used when it should be. which causes a lot more memory and cpu to be used than is necessary.

instead of camera.setPreviewCallback(); camview really should make use of camera.setPreviewCallbackWithBuffer();

http://developer.android.com/reference/android/hardware/Camera.html#setPreviewCallbackWithBuffer(android.hardware.Camera.PreviewCallback)

http://developer.android.com/reference/android/hardware/Camera.html#addCallbackBuffer(byte[])

**Comment by livotov** [comment]
fix for both  issues is not in 2.1.0-SNAPSHOT and in master as well, so you can try. The CAMView project was updated accordingly to support CallbackBuffer.

Note that API has changed a little for both CAMView and ZXScanLib projects.

Let me know how it runs at your side
