### ISSUE TITLE
ScannerFragment error

### ISSUE THREAD

**Issue by windlessuser** [LivotovLabs/zxscanlib#24]
java.lang.ClassCastException: eu.livotov.zxscan.ScannerView cannot be cast to eu.livotov.labs.android.camview.CAMView

code:
````java
ScannerFragment fragment = new ScannerFragment();
getSupportFragmentManager().beginTransaction().add(R.id.fragment_container, fragment).commit();
```

**Comment by livotov** [comment]
Thanks for reporting,
this was already fixed in 2.0.1-SNAPSHOT
