### ISSUE TITLE
Too many threads

### ISSUE THREAD

**Issue by wsgfz** [LivotovLabs/zxscanlib#27]
It's not a good idea to start a thread every frame.
I can't recognize any QR code with the 2.1.0.

**Comment by livotov** [comment]
Basically there is only one thread at a time, because we do not receive next frame until the current frame decoding process is finished.

**Comment by livotov** [comment]
anyway, already upgraded processing thread to a messaging queue. please try.

**Comment by livotov** [comment]
pushed to both master and snapshot
