### ISSUE TITLE
No option to throttle scanning rate

### ISSUE THREAD

**Issue by edmundnoble** [LivotovLabs/zxscanlib#30]
Right now, every frame captured is scanned. This can result in extra battery usage and sluggishness on less performant devices, and testing indicates that less scanning (every 5 frames) works just as well. This can be worked in as a property of ScannerView.

**Comment by livotov** [comment]
good point, thanks !

**Comment by silverballer** [comment]
I've got a pull request in to fix this. If you have any suggestions (disable throttling by default, different default throttling period, etc.) please let me know.

**Comment by livotov** [comment]
cool, thanks !

What do you think, maybe we need to return "false" in case when the throttle condition is met and we want to skip the frame from processing. This will stop receiving any new preview frames from the camera during the "silent" period - this could also free up the phone resources. But in such case someone needs to call camera.enablePreviewGrabbing() at the end of "silent" period, so probably a timer may be started here, which will call camera.enablePreviewGrabbing() on timeout

**Comment by shahbaz-man** [comment]
Yeah the constant scanning makes my ui unreactive to touch events and back button presses. It takes a good 10 seconds for them to register.

**Comment by livotov** [comment]
fixed in master
