### ISSUE TITLE
How to use front facing camera

### ISSUE THREAD

**Issue by muzammil-hussain** [LivotovLabs/zxscanlib#32]
Great work. Just one thing i need to change for my app requirement. I want to force app to use front facing camera. Can you please add that in custom settings

**Comment by livotov** [comment]
good point !
will add to the set of configuration options.

**Comment by livotov** [comment]
updated ScannerView API as follows:

1) get the list of available cameras via getAvailableCameras()
2) call startScanner overloaded method, specifying the camera object of your interest
