### ISSUE TITLE
how to detect QRcode rotation?

### ISSUE THREAD

**Issue by yamol700304** [LivotovLabs/zxscanlib#33]
can I detetct QRcode rotation ?

**Comment by livotov** [comment]
what do you mean under "QRcode rotation" ?
QR codes are currently read in any position

**Comment by livotov** [comment]
closing as no response received

**Comment by yamol700304** [comment]
I need detect qrcode's  rotate(0°,90°,180°,270°)  , not any position , is it ok?

**Comment by livotov** [comment]
Sorry, but did not understand you. qr-codes are recognized with any position/rotation. Why and where you need to rotate it ?

**Comment by livotov** [comment]
IMPORTANT INFORMATION - this project is now merged with another one, called CAMView: https://github.com/LivotovLabs/CamView

All future development of this scanner library will happen inside the CAMView repository. Please post your issues and download sources, new snapshots and releases there: https://github.com/LivotovLabs/CamView

We believe both ZXScanLib and CAMView have a lot of common (moreover, ZXScanLib depends on a CAMView), so having it as a single solid project will boost productivity and add more transparency.

All previous ZXScanLib releases will remain in the maven repo forever, so no current production apps should be affected.
