### ISSUE TITLE
Performance Issues with version +2.0.0

### ISSUE THREAD

**Issue by condesales** [LivotovLabs/zxscanlib#34]
I was using version `zxscanlib-2.0.0-SNAPSHOT ` before and **HAD** to update version to 2.0.0 because the SNAPSHOT one was removed from repositories.

Now my app it's really slow reading the codes. It seems that the library is doing too much work on the main thread, cause all UI feedbacks are really slow (button clicks, back press and so on...)

**Comment by livotov** [comment]
Current snapshot is 2.1.1, please try it. main thread issues was addressed there
