### ISSUE TITLE
Cannot go back

### ISSUE THREAD

**Issue by tefotazo** [LivotovLabs/zxscanlib#35]
I have no idea why, but when the scanner starts, never can go back before stopping the scanner. The hardware button back not responds. The only way to go back, is scanning a code (then the method onCodeScanned is triggered and I stop the scanner on it).

I have a Samsung Galaxy S4 (I9500)

**Comment by livotov** [comment]
did you use the latest snapshot ?
similar issue were addresses there and there should be no more problems with the back button

**Comment by AnyOfYou** [comment]
Same issue, It's just running slow when scanner is working.

**Comment by livotov** [comment]
IMPORTANT INFORMATION - this project is now merged with another one, called CAMView: https://github.com/LivotovLabs/CamView

All future development of this scanner library will happen inside the CAMView repository. Please post your issues and download sources, new snapshots and releases there: https://github.com/LivotovLabs/CamView

We believe both ZXScanLib and CAMView have a lot of common (moreover, ZXScanLib depends on a CAMView), so having it as a single solid project will boost productivity and add more transparency.

All previous ZXScanLib releases will remain in the maven repo forever, so no current production apps should be affected.
