### ISSUE TITLE
Keep camera but stop detecting

### ISSUE THREAD

**Issue by BadChoice** [LivotovLabs/zxscanlib#37]
Is there a way to keep camera on but stop trying to detect more codes?

**Comment by livotov** [comment]
What is the goal for this feature ?

Basically, for a QR code scanner you wan to do scan and quit on first scanned code or perform continuous scan until finished manually by the user or by some condition (e.g. number of barcodes processed, etc).

**Comment by livotov** [comment]
you can check with the https://github.com/LivotovLabs/CAMView master branch right now (please see the bundled demo app). Official readme and maven repo will be updated within a day or two

**Comment by livotov** [comment]
General usage:

```
ScannerLiveView scanner = findViewById(R.id......);
scanner.setScannerViewEventListener(...);
scanner.startScanner();
```

**Comment by livotov** [comment]
IMPORTANT INFORMATION - this project is now merged with another one, called CAMView: https://github.com/LivotovLabs/CamView

All future development of this scanner library will happen inside the CAMView repository. Please post your issues and download sources, new snapshots and releases there: https://github.com/LivotovLabs/CamView

We believe both ZXScanLib and CAMView have a lot of common (moreover, ZXScanLib depends on a CAMView), so having it as a single solid project will boost productivity and add more transparency.

All previous ZXScanLib releases will remain in the maven repo forever, so no current production apps should be affected.
