### ISSUE TITLE
Not scanning in 2.1.1-SNAPSHOT

### ISSUE THREAD

**Issue by wlky** [LivotovLabs/zxscanlib#38]
Hey, I just tested the demo app in the most current snapshot and noticed that onCodeScanned is never triggered.
I traced the problem to onPreviewData never being called in the ScannerView, so the problem might also be in CAMView.

Is there a fix for that in sight?^^

**Comment by tryadelion** [comment]
i seem to have the same problem, using the 2.1.1 snapshot as view inside a fragment, it doesn't scan or trigger events.

**Comment by livotov** [comment]
yep, CAMView project is being refactored at the moment. Once done, ZXScanLib will use it and I hope those weird problems will go away

**Comment by tryadelion** [comment]
any idea when it'll be out?

**Comment by livotov** [comment]
still in progress, as busy on other tasks, unfortunately

**Comment by mtangoo** [comment]
Whats the solution for us using android Studio with the same issue?

**Comment by livotov** [comment]
you can take current LivotovLabs/CamView sources from the development/1.x-support branch and try it  with the zxscanlib or wait 1-2 days when we form and publish a new snapshot, so you can reference it in the gradle

**Comment by mtangoo** [comment]
do they have a jar file or I have to build it?

**Comment by livotov** [comment]
you have to build it. you can simply include the libraries as local modules and reference them in settings.gradle like 

```
include ':zxscanlib', ':camview'
```

**Comment by mtangoo** [comment]
I hope building it is easy ;)

**Comment by livotov** [comment]
you can check with the https://github.com/LivotovLabs/CAMView master branch right now (please see the bundled demo app). Official readme and maven repo will be updated within a day or two

**Comment by livotov** [comment]
General usage:

```
ScannerLiveView scanner = findViewById(R.id......);
scanner.setScannerViewEventListener(...);
scanner.startScanner();
```

**Comment by livotov** [comment]
IMPORTANT INFORMATION - this project is now merged with another one, called CAMView: https://github.com/LivotovLabs/CamView

All future development of this scanner library will happen inside the CAMView repository. Please post your issues and download sources, new snapshots and releases there: https://github.com/LivotovLabs/CamView

We believe both ZXScanLib and CAMView have a lot of common (moreover, ZXScanLib depends on a CAMView), so having it as a single solid project will boost productivity and add more transparency.

All previous ZXScanLib releases will remain in the maven repo forever, so no current production apps should be affected.
