### ISSUE TITLE
since 2.1.1 , camera doesn't detect QR codes

### ISSUE THREAD

**Issue by tryadelion** [LivotovLabs/zxscanlib#39]
it doesn't detect any qr code, at all.

**Comment by livotov** [comment]
you can check with the https://github.com/LivotovLabs/CAMView master branch right now (please see the bundled demo app). Official readme and maven repo will be updated within a day or two

**Comment by livotov** [comment]
General usage:

```
ScannerLiveView scanner = findViewById(R.id......);
scanner.setScannerViewEventListener(...);
scanner.startScanner();
```

**Comment by livotov** [comment]
IMPORTANT INFORMATION - this project is now merged with another one, called CAMView: https://github.com/LivotovLabs/CamView

All future development of this scanner library will happen inside the CAMView repository. Please post your issues and download sources, new snapshots and releases there: https://github.com/LivotovLabs/CamView

We believe both ZXScanLib and CAMView have a lot of common (moreover, ZXScanLib depends on a CAMView), so having it as a single solid project will boost productivity and add more transparency.

All previous ZXScanLib releases will remain in the maven repo forever, so no current production apps should be affected.
