### ISSUE TITLE
Merge CAMView into ZXScanLib project

### ISSUE THREAD

**Issue by livotov** [LivotovLabs/zxscanlib#40]
Merge CAMView into ZXScanLib project (and into the projects namespace too) to simplify library management. This also confuses some users too.

**Comment by livotov** [comment]
finally decided to make a reverse merge. ZXScanLib will join CAMView, so there will be a single project CAMView for both use cases - displaying live camera picture in a view or scanning barcodes.  This will happen in a version 2.x of the CAMView.

**Comment by mtangoo** [comment]
Will this repository stay or will go?

**Comment by livotov** [comment]
Once merge will be performed, this repository will stay at its current state (with the proper deprecated/moved message), as well as all published maven artefacts, so current apps using zxscanlib project will not be affected at all. Simply the CAMView project will receive all ZXScanLib code and further development will happen there.

**Comment by mtangoo** [comment]
:+1:
