### ISSUE TITLE
galaxy s6 camera preview is stretched

### ISSUE THREAD

**Issue by Leaghte** [LivotovLabs/zxscanlib#42]
Hi , i tested lib on few devices. Working fine, but on galaxy s6 camera preview is stretched. See the picture below. HUD is not in the middle  :( 
![screenshot_2015-08-18-14-34-36](https://cloud.githubusercontent.com/assets/7208681/9330071/15d0dcfe-45b7-11e5-931f-df5f3b6a39fd.png)

**Comment by livotov** [comment]
IMPORTANT INFORMATION - this project is now merged with another one, called CAMView: https://github.com/LivotovLabs/CamView

All future development of this scanner library will happen inside the CAMView repository. Please post your issues and download sources, new snapshots and releases there: https://github.com/LivotovLabs/CamView

We believe both ZXScanLib and CAMView have a lot of common (moreover, ZXScanLib depends on a CAMView), so having it as a single solid project will boost productivity and add more transparency.

All previous ZXScanLib releases will remain in the maven repo forever, so no current production apps should be affected.
